### ISSUE TITLE
Add ability to configure Payload, Topic, Headers...

### ISSUE THREAD

**Issue by yan-kisen** [yn5/webhook-contentful-app#4]
I already posted on Slack, but adding here to start the discussion.

---

Do you have any plan to update it to attach `payload`, `topic`, etc?

I don't really understand the usefulness without that context.

---

It would be really cool to be able if you could reference a preexisting Webhook from the App Settings, but I am not seeing a way to create one without a trigger. (Except the workaround in my screenshot, but I haven't been able to test it yet)

Is it possible to trigger a webhook via API call?

I guess at that point you could just make the webhook POST directly from the UI Extension

<img width="1320" alt="image" src="https://user-images.githubusercontent.com/1116995/90871774-97701e00-e369-11ea-9da5-53d87b750c82.png">

**Comment by yn5** [comment]
Thanks for pointing out that some context would be helpful, if this make sense and clarifies the purpose I’ll add it to the README too:

We ran into very long build queues on our build system using the available Webhook configuration since the site we’re using this for has become quite large, therefore builds take a long time and out build system (Vercel) unfortunately does not cancel queued builds if new ones are triggered (like how some CI/CD handle this potential issue). We have been looking at the filter options in the default Webhook configuration to reduce the amount of webhook triggers but this will have content editors to “artificially” trigger an event since they might have just made a small change in one of the nested content items, and did not change an item of the type the filter is applied to and therefore can’t naturally save or publish that to trigger a build. We basically wanted to provide the ability to be able to trigger a build from any content type, but not being forced to. With this app content editors can just make all the changes they need, preview them in “preview mode” and trigger a build when they are done.

I’ve also looked into referencing a preexisting webhook, but I didn’t find a way to get to that configuration from within this app (do you know there is a way and there is something I missed?). And as you point out it is indeed not possible to create one without a trigger although I like your suggestion to hack around it by creating an “impossible” trigger 😊

Vercel just provides you with an URL for the webhook, therefore we have no need for more configuration than just that URL currently. But I can add a field to configure a custom payload to be sent with the POST request. I’m not quite sure what you mean by `topic` though?

**Comment by yn5** [comment]
@yan-kisen As I understand from our conversation on Slack your use case is quite far from the purpose of this app extension. But nonetheless, would it be helpful for you if I added an option to supply custom JSON to send along with the webhook? Or won't you be using this app extension in any case?

**Comment by yan-kisen** [comment]
Sorry, I don't have notifications enabled for GitHub.

I won't be using this App _directly_, but I am inspired by it 🙂

Regardless, adding the ability to specify a payload seems like a standard use-case for somebody trying to add a webhook trigger.

I'm not sure how to best approach generically via `AppConfig`, but a start could be sending the ID of the Source Entry. Something like:

```
{ entryId: sdk.entry.getSys().id }
```

I will share my final creation with you once it's complete.

**Comment by yn5** [comment]
Yes completely agree. But if you won't use it I won't prioritise it and will close the issue for now. As I prefer adding functionality only if it will actually be used. And since Vercel does not require any payload for the webhooks to be triggered, I have no need either.

For the future reader that has the same or similar requirements and will actually make use of them, please feel free to open a new issue!

Looking forward to see your work! @yan-kisen
